using PkManager.Server.Controllers;

namespace PkManager.Server.Helpers;

/// <summary>
/// 3DS GeoLocation 数据 — 从 PKHeX 资源文件提取的中文国家/地区名称
/// </summary>
public static class GeoData
{
    public static readonly List<ResourceItem> Countries = new()
    {
        new() { Id = 1, Name = "日本" },
        new() { Id = 8, Name = "安圭拉" },
        new() { Id = 9, Name = "安提瓜和巴布达" },
        new() { Id = 10, Name = "阿根廷" },
        new() { Id = 11, Name = "阿鲁巴" },
        new() { Id = 12, Name = "巴哈马" },
        new() { Id = 13, Name = "巴巴多斯" },
        new() { Id = 14, Name = "伯利兹" },
        new() { Id = 15, Name = "玻利维亚" },
        new() { Id = 16, Name = "巴西" },
        new() { Id = 17, Name = "英属维尔京群岛" },
        new() { Id = 18, Name = "加拿大" },
        new() { Id = 20, Name = "开曼群岛" },
        new() { Id = 21, Name = "智利" },
        new() { Id = 22, Name = "哥伦比亚" },
        new() { Id = 23, Name = "哥斯达黎加" },
        new() { Id = 24, Name = "多米尼克" },
        new() { Id = 25, Name = "多米尼加共和国" },
        new() { Id = 26, Name = "厄瓜多尔" },
        new() { Id = 27, Name = "萨尔瓦多" },
        new() { Id = 28, Name = "法属圭亚那" },
        new() { Id = 29, Name = "格林纳达" },
        new() { Id = 30, Name = "瓜德罗普" },
        new() { Id = 31, Name = "危地马拉" },
        new() { Id = 32, Name = "圭亚那" },
        new() { Id = 33, Name = "海地" },
        new() { Id = 34, Name = "洪都拉斯" },
        new() { Id = 35, Name = "牙买加" },
        new() { Id = 36, Name = "马提尼克" },
        new() { Id = 37, Name = "墨西哥" },
        new() { Id = 38, Name = "蒙特塞拉特" },
        new() { Id = 39, Name = "荷属安的列斯" },
        new() { Id = 40, Name = "尼加拉瓜" },
        new() { Id = 41, Name = "巴拿马" },
        new() { Id = 42, Name = "巴拉圭" },
        new() { Id = 43, Name = "秘鲁" },
        new() { Id = 44, Name = "圣基茨和尼维斯" },
        new() { Id = 45, Name = "圣卢西亚" },
        new() { Id = 46, Name = "圣文森特和格林纳丁斯" },
        new() { Id = 47, Name = "苏里南" },
        new() { Id = 48, Name = "特立尼达和多巴哥" },
        new() { Id = 49, Name = "特克斯和凯科斯群岛" },
        new() { Id = 50, Name = "美国" },
        new() { Id = 51, Name = "乌拉圭" },
        new() { Id = 52, Name = "美属维尔京群岛" },
        new() { Id = 53, Name = "委内瑞拉" },
        new() { Id = 64, Name = "阿尔巴尼亚" },
        new() { Id = 65, Name = "澳大利亚" },
        new() { Id = 66, Name = "奥地利" },
        new() { Id = 67, Name = "比利时" },
        new() { Id = 68, Name = "波黑" },
        new() { Id = 69, Name = "博茨瓦纳" },
        new() { Id = 70, Name = "保加利亚" },
        new() { Id = 71, Name = "克罗地亚" },
        new() { Id = 72, Name = "塞浦路斯" },
        new() { Id = 73, Name = "捷克" },
        new() { Id = 74, Name = "丹麦" },
        new() { Id = 75, Name = "爱沙尼亚" },
        new() { Id = 76, Name = "芬兰" },
        new() { Id = 77, Name = "法国" },
        new() { Id = 78, Name = "德国" },
        new() { Id = 79, Name = "希腊" },
        new() { Id = 80, Name = "匈牙利" },
        new() { Id = 81, Name = "冰岛" },
        new() { Id = 82, Name = "爱尔兰" },
        new() { Id = 83, Name = "意大利" },
        new() { Id = 84, Name = "拉脱维亚" },
        new() { Id = 85, Name = "列支敦士登" },
        new() { Id = 86, Name = "立陶宛" },
        new() { Id = 87, Name = "卢森堡" },
        new() { Id = 88, Name = "马其顿" },
        new() { Id = 89, Name = "马耳他" },
        new() { Id = 90, Name = "黑山" },
        new() { Id = 91, Name = "莫桑比克" },
        new() { Id = 92, Name = "纳米比亚" },
        new() { Id = 93, Name = "荷兰" },
        new() { Id = 94, Name = "新西兰" },
        new() { Id = 95, Name = "挪威" },
        new() { Id = 96, Name = "波兰" },
        new() { Id = 97, Name = "葡萄牙" },
        new() { Id = 98, Name = "罗马尼亚" },
        new() { Id = 99, Name = "俄罗斯" },
        new() { Id = 100, Name = "塞尔维亚" },
        new() { Id = 101, Name = "斯洛伐克" },
        new() { Id = 102, Name = "斯洛文尼亚" },
        new() { Id = 103, Name = "南非" },
        new() { Id = 104, Name = "西班牙" },
        new() { Id = 105, Name = "瑞典" },
        new() { Id = 106, Name = "瑞士" },
        new() { Id = 107, Name = "土耳其" },
        new() { Id = 108, Name = "英国" },
        new() { Id = 109, Name = "赞比亚" },
        new() { Id = 110, Name = "津巴布韦" },
        new() { Id = 128, Name = "台湾" },
        new() { Id = 136, Name = "韩国" },
        new() { Id = 144, Name = "中国" },
    };

    public static readonly Dictionary<int, List<ResourceItem>> Regions = new()
    {
        // Japan (1) — 都道府県
        [1] = new() {
            new(){Id=0,Name="—"}, new(){Id=1,Name="北海道"}, new(){Id=2,Name="青森県"},
            new(){Id=3,Name="岩手県"}, new(){Id=4,Name="宮城県"}, new(){Id=5,Name="秋田県"},
            new(){Id=6,Name="山形県"}, new(){Id=7,Name="福島県"}, new(){Id=8,Name="茨城県"},
            new(){Id=9,Name="栃木県"}, new(){Id=10,Name="群馬県"}, new(){Id=11,Name="埼玉県"},
            new(){Id=12,Name="千葉県"}, new(){Id=13,Name="東京都"}, new(){Id=14,Name="神奈川県"},
            new(){Id=15,Name="新潟県"}, new(){Id=16,Name="富山県"}, new(){Id=17,Name="石川県"},
            new(){Id=18,Name="福井県"}, new(){Id=19,Name="山梨県"}, new(){Id=20,Name="長野県"},
            new(){Id=21,Name="岐阜県"}, new(){Id=22,Name="静岡県"}, new(){Id=23,Name="愛知県"},
            new(){Id=24,Name="三重県"}, new(){Id=25,Name="滋賀県"}, new(){Id=26,Name="京都府"},
            new(){Id=27,Name="大阪府"}, new(){Id=28,Name="兵庫県"}, new(){Id=29,Name="奈良県"},
            new(){Id=30,Name="和歌山県"}, new(){Id=31,Name="鳥取県"}, new(){Id=32,Name="島根県"},
            new(){Id=33,Name="岡山県"}, new(){Id=34,Name="広島県"}, new(){Id=35,Name="山口県"},
            new(){Id=36,Name="徳島県"}, new(){Id=37,Name="香川県"}, new(){Id=38,Name="愛媛県"},
            new(){Id=39,Name="高知県"}, new(){Id=40,Name="福岡県"}, new(){Id=41,Name="佐賀県"},
            new(){Id=42,Name="長崎県"}, new(){Id=43,Name="熊本県"}, new(){Id=44,Name="大分県"},
            new(){Id=45,Name="宮崎県"}, new(){Id=46,Name="鹿児島県"}, new(){Id=47,Name="沖縄県"},
        },
        // USA (50)
        [50] = new() {
            new(){Id=0,Name="—"}, new(){Id=1,Name="亚拉巴马州"}, new(){Id=2,Name="阿拉斯加州"},
            new(){Id=3,Name="亚利桑那州"}, new(){Id=4,Name="阿肯色州"}, new(){Id=5,Name="加利福尼亚州"},
            new(){Id=6,Name="科罗拉多州"}, new(){Id=7,Name="康涅狄格州"}, new(){Id=8,Name="特拉华州"},
            new(){Id=9,Name="佛罗里达州"}, new(){Id=10,Name="佐治亚州"}, new(){Id=11,Name="夏威夷州"},
            new(){Id=12,Name="爱达荷州"}, new(){Id=13,Name="伊利诺伊州"}, new(){Id=14,Name="印第安纳州"},
            new(){Id=15,Name="艾奥瓦州"}, new(){Id=16,Name="堪萨斯州"}, new(){Id=17,Name="肯塔基州"},
            new(){Id=18,Name="路易斯安那州"}, new(){Id=19,Name="缅因州"}, new(){Id=20,Name="马里兰州"},
            new(){Id=21,Name="马萨诸塞州"}, new(){Id=22,Name="密歇根州"}, new(){Id=23,Name="明尼苏达州"},
            new(){Id=24,Name="密西西比州"}, new(){Id=25,Name="密苏里州"}, new(){Id=26,Name="蒙大拿州"},
            new(){Id=27,Name="内布拉斯加州"}, new(){Id=28,Name="内华达州"}, new(){Id=29,Name="新罕布什尔州"},
            new(){Id=30,Name="新泽西州"}, new(){Id=31,Name="新墨西哥州"}, new(){Id=32,Name="纽约州"},
            new(){Id=33,Name="北卡罗来纳州"}, new(){Id=34,Name="北达科他州"}, new(){Id=35,Name="俄亥俄州"},
            new(){Id=36,Name="俄克拉何马州"}, new(){Id=37,Name="俄勒冈州"}, new(){Id=38,Name="宾夕法尼亚州"},
            new(){Id=39,Name="罗得岛州"}, new(){Id=40,Name="南卡罗来纳州"}, new(){Id=41,Name="南达科他州"},
            new(){Id=42,Name="田纳西州"}, new(){Id=43,Name="得克萨斯州"}, new(){Id=44,Name="犹他州"},
            new(){Id=45,Name="佛蒙特州"}, new(){Id=46,Name="弗吉尼亚州"}, new(){Id=47,Name="华盛顿州"},
            new(){Id=48,Name="西弗吉尼亚州"}, new(){Id=49,Name="威斯康星州"}, new(){Id=50,Name="怀俄明州"},
            new(){Id=51,Name="哥伦比亚特区"},
        },
    };
}
